/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'marketType' : MarketType,
  'ticker' : string,
  'name' : string,
}
export interface FiatAssetCacheEntry {
  'expired' : boolean,
  'assets' : Array<Asset>,
  'timestamp' : bigint,
}
export interface FiatVPS1ValidationResult {
  'validationStatus' : { 'valid' : null } |
    { 'invalid' : null },
  'rawResponseBody' : string,
  'isTruncated' : boolean,
  'errorMessage' : [] | [string],
  'requestedUrl' : string,
  'timestamp' : bigint,
}
export type HTTPSUrl = string;
export type MarketType = { 'stocks' : null } |
  { 'commodities' : null } |
  { 'fiat' : null } |
  { 'crypto' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cacheFiatVPS1Data' : ActorMethod<[string, Array<Asset>], boolean>,
  'expireFiatAssetCacheEntries' : ActorMethod<[Array<string>], bigint>,
  'fetchCommoditiesData' : ActorMethod<[HTTPSUrl], string>,
  'fetchCryptoData' : ActorMethod<[HTTPSUrl], string>,
  'fetchExternalData' : ActorMethod<[string], string>,
  'fetchFiatData' : ActorMethod<[HTTPSUrl], string>,
  'fetchFiatVPS1Data' : ActorMethod<[], string>,
  'fetchStocksData' : ActorMethod<[HTTPSUrl], string>,
  'getCachedFiatAssets' : ActorMethod<[string], [] | [FiatAssetCacheEntry]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFiatCacheMetaData' : ActorMethod<[], Array<[string, bigint, boolean]>>,
  'getFiatVPS1ValidationResult' : ActorMethod<
    [],
    [] | [FiatVPS1ValidationResult]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];