/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MarketType = IDL.Variant({
  'stocks' : IDL.Null,
  'commodities' : IDL.Null,
  'fiat' : IDL.Null,
  'crypto' : IDL.Null,
});
export const Asset = IDL.Record({
  'marketType' : MarketType,
  'ticker' : IDL.Text,
  'name' : IDL.Text,
});
export const HTTPSUrl = IDL.Text;
export const FiatAssetCacheEntry = IDL.Record({
  'expired' : IDL.Bool,
  'assets' : IDL.Vec(Asset),
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FiatVPS1ValidationResult = IDL.Record({
  'validationStatus' : IDL.Variant({
    'valid' : IDL.Null,
    'invalid' : IDL.Null,
  }),
  'rawResponseBody' : IDL.Text,
  'isTruncated' : IDL.Bool,
  'errorMessage' : IDL.Opt(IDL.Text),
  'requestedUrl' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cacheFiatVPS1Data' : IDL.Func([IDL.Text, IDL.Vec(Asset)], [IDL.Bool], []),
  'expireFiatAssetCacheEntries' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'fetchCommoditiesData' : IDL.Func([HTTPSUrl], [IDL.Text], []),
  'fetchCryptoData' : IDL.Func([HTTPSUrl], [IDL.Text], []),
  'fetchExternalData' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchFiatData' : IDL.Func([HTTPSUrl], [IDL.Text], []),
  'fetchFiatVPS1Data' : IDL.Func([], [IDL.Text], []),
  'fetchStocksData' : IDL.Func([HTTPSUrl], [IDL.Text], []),
  'getCachedFiatAssets' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FiatAssetCacheEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFiatCacheMetaData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int, IDL.Bool))],
      ['query'],
    ),
  'getFiatVPS1ValidationResult' : IDL.Func(
      [],
      [IDL.Opt(FiatVPS1ValidationResult)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MarketType = IDL.Variant({
    'stocks' : IDL.Null,
    'commodities' : IDL.Null,
    'fiat' : IDL.Null,
    'crypto' : IDL.Null,
  });
  const Asset = IDL.Record({
    'marketType' : MarketType,
    'ticker' : IDL.Text,
    'name' : IDL.Text,
  });
  const HTTPSUrl = IDL.Text;
  const FiatAssetCacheEntry = IDL.Record({
    'expired' : IDL.Bool,
    'assets' : IDL.Vec(Asset),
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FiatVPS1ValidationResult = IDL.Record({
    'validationStatus' : IDL.Variant({
      'valid' : IDL.Null,
      'invalid' : IDL.Null,
    }),
    'rawResponseBody' : IDL.Text,
    'isTruncated' : IDL.Bool,
    'errorMessage' : IDL.Opt(IDL.Text),
    'requestedUrl' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cacheFiatVPS1Data' : IDL.Func([IDL.Text, IDL.Vec(Asset)], [IDL.Bool], []),
    'expireFiatAssetCacheEntries' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'fetchCommoditiesData' : IDL.Func([HTTPSUrl], [IDL.Text], []),
    'fetchCryptoData' : IDL.Func([HTTPSUrl], [IDL.Text], []),
    'fetchExternalData' : IDL.Func([IDL.Text], [IDL.Text], []),
    'fetchFiatData' : IDL.Func([HTTPSUrl], [IDL.Text], []),
    'fetchFiatVPS1Data' : IDL.Func([], [IDL.Text], []),
    'fetchStocksData' : IDL.Func([HTTPSUrl], [IDL.Text], []),
    'getCachedFiatAssets' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FiatAssetCacheEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFiatCacheMetaData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int, IDL.Bool))],
        ['query'],
      ),
    'getFiatVPS1ValidationResult' : IDL.Func(
        [],
        [IDL.Opt(FiatVPS1ValidationResult)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };