/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FiatVPS1ValidationResult {
    validationStatus: Variant_valid_invalid;
    rawResponseBody: string;
    isTruncated: boolean;
    errorMessage?: string;
    requestedUrl: string;
    timestamp: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface StocksVPS1RawValidationResult {
    validationStatus: Variant_valid_invalid;
    rawResponseBody: string;
    isTruncated: boolean;
    errorMessage?: string;
    requestedUrl: string;
    timestamp: bigint;
}
export interface FiatAssetCacheEntry {
    expired: boolean;
    assets: Array<Asset>;
    timestamp: bigint;
}
export interface CommoditiesVPS1ValidationResult {
    validationStatus: Variant_valid_invalid;
    rawResponseBody: string;
    isTruncated: boolean;
    errorMessage?: string;
    requestedUrl: string;
    timestamp: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface StocksVPS1ValidationResult {
    validationStatus: Variant_valid_invalid;
    rawResponseBody: string;
    isTruncated: boolean;
    errorMessage?: string;
    requestedUrl: string;
    timestamp: bigint;
}
export interface Asset {
    marketType: MarketType;
    ticker: string;
    name: string;
}
export interface UserProfile {
    name: string;
}
export type HTTPSUrl = string;
export enum MarketType {
    stocks = "stocks",
    commodities = "commodities",
    fiat = "fiat",
    crypto = "crypto"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_valid_invalid {
    valid = "valid",
    invalid = "invalid"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cacheFiatVPS1Data(cacheId: string, assets: Array<Asset>): Promise<boolean>;
    expireFiatAssetCacheEntries(cacheIds: Array<string>): Promise<bigint>;
    fetchCommoditiesData(url: HTTPSUrl): Promise<string>;
    fetchCommoditiesVPS1Data(): Promise<string>;
    fetchCryptoData(url: HTTPSUrl): Promise<string>;
    fetchExternalData(_url: string): Promise<string>;
    fetchFiatData(url: HTTPSUrl): Promise<string>;
    fetchFiatVPS1Data(): Promise<string>;
    fetchStocksData(url: HTTPSUrl): Promise<string>;
    fetchStocksVPS1Chunk(endpointNumber: bigint, chunkIndex: bigint): Promise<void>;
    fetchStocksVPS1Raw(endpointNumber: bigint): Promise<void>;
    getAllStocksValidationResults(): Promise<Array<[string, StocksVPS1ValidationResult]>>;
    getCachedFiatAssets(cacheId: string): Promise<FiatAssetCacheEntry | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommoditiesVPS1ValidationResult(): Promise<CommoditiesVPS1ValidationResult | null>;
    getFiatCacheMetaData(): Promise<Array<[string, bigint, boolean]>>;
    getFiatVPS1ValidationResult(): Promise<FiatVPS1ValidationResult | null>;
    getStocksVPS1RawValidationResult(): Promise<StocksVPS1RawValidationResult | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { Asset as _Asset, CommoditiesVPS1ValidationResult as _CommoditiesVPS1ValidationResult, FiatAssetCacheEntry as _FiatAssetCacheEntry, FiatVPS1ValidationResult as _FiatVPS1ValidationResult, MarketType as _MarketType, StocksVPS1RawValidationResult as _StocksVPS1RawValidationResult, StocksVPS1ValidationResult as _StocksVPS1ValidationResult, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cacheFiatVPS1Data(arg0: string, arg1: Array<Asset>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cacheFiatVPS1Data(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cacheFiatVPS1Data(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async expireFiatAssetCacheEntries(arg0: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.expireFiatAssetCacheEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.expireFiatAssetCacheEntries(arg0);
            return result;
        }
    }
    async fetchCommoditiesData(arg0: HTTPSUrl): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCommoditiesData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCommoditiesData(arg0);
            return result;
        }
    }
    async fetchCommoditiesVPS1Data(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCommoditiesVPS1Data();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCommoditiesVPS1Data();
            return result;
        }
    }
    async fetchCryptoData(arg0: HTTPSUrl): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchCryptoData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchCryptoData(arg0);
            return result;
        }
    }
    async fetchExternalData(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchExternalData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchExternalData(arg0);
            return result;
        }
    }
    async fetchFiatData(arg0: HTTPSUrl): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchFiatData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchFiatData(arg0);
            return result;
        }
    }
    async fetchFiatVPS1Data(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchFiatVPS1Data();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchFiatVPS1Data();
            return result;
        }
    }
    async fetchStocksData(arg0: HTTPSUrl): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchStocksData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchStocksData(arg0);
            return result;
        }
    }
    async fetchStocksVPS1Chunk(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchStocksVPS1Chunk(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchStocksVPS1Chunk(arg0, arg1);
            return result;
        }
    }
    async fetchStocksVPS1Raw(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchStocksVPS1Raw(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchStocksVPS1Raw(arg0);
            return result;
        }
    }
    async getAllStocksValidationResults(): Promise<Array<[string, StocksVPS1ValidationResult]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStocksValidationResults();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStocksValidationResults();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCachedFiatAssets(arg0: string): Promise<FiatAssetCacheEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCachedFiatAssets(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCachedFiatAssets(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommoditiesVPS1ValidationResult(): Promise<CommoditiesVPS1ValidationResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommoditiesVPS1ValidationResult();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommoditiesVPS1ValidationResult();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFiatCacheMetaData(): Promise<Array<[string, bigint, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFiatCacheMetaData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFiatCacheMetaData();
            return result;
        }
    }
    async getFiatVPS1ValidationResult(): Promise<FiatVPS1ValidationResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFiatVPS1ValidationResult();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFiatVPS1ValidationResult();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStocksVPS1RawValidationResult(): Promise<StocksVPS1RawValidationResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStocksVPS1RawValidationResult();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStocksVPS1RawValidationResult();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_Asset_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Asset): Asset {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_CommoditiesVPS1ValidationResult_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommoditiesVPS1ValidationResult): CommoditiesVPS1ValidationResult {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_FiatAssetCacheEntry_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FiatAssetCacheEntry): FiatAssetCacheEntry {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_FiatVPS1ValidationResult_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FiatVPS1ValidationResult): FiatVPS1ValidationResult {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_MarketType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketType): MarketType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_StocksVPS1RawValidationResult_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StocksVPS1RawValidationResult): StocksVPS1RawValidationResult {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_StocksVPS1ValidationResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StocksVPS1ValidationResult): StocksVPS1ValidationResult {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FiatAssetCacheEntry]): FiatAssetCacheEntry | null {
    return value.length === 0 ? null : from_candid_FiatAssetCacheEntry_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CommoditiesVPS1ValidationResult]): CommoditiesVPS1ValidationResult | null {
    return value.length === 0 ? null : from_candid_CommoditiesVPS1ValidationResult_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FiatVPS1ValidationResult]): FiatVPS1ValidationResult | null {
    return value.length === 0 ? null : from_candid_FiatVPS1ValidationResult_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StocksVPS1RawValidationResult]): StocksVPS1RawValidationResult | null {
    return value.length === 0 ? null : from_candid_StocksVPS1RawValidationResult_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    validationStatus: {
        valid: null;
    } | {
        invalid: null;
    };
    rawResponseBody: string;
    isTruncated: boolean;
    errorMessage: [] | [string];
    requestedUrl: string;
    timestamp: bigint;
}): {
    validationStatus: Variant_valid_invalid;
    rawResponseBody: string;
    isTruncated: boolean;
    errorMessage?: string;
    requestedUrl: string;
    timestamp: bigint;
} {
    return {
        validationStatus: from_candid_variant_n12(_uploadFile, _downloadFile, value.validationStatus),
        rawResponseBody: value.rawResponseBody,
        isTruncated: value.isTruncated,
        errorMessage: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.errorMessage)),
        requestedUrl: value.requestedUrl,
        timestamp: value.timestamp
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expired: boolean;
    assets: Array<_Asset>;
    timestamp: bigint;
}): {
    expired: boolean;
    assets: Array<Asset>;
    timestamp: bigint;
} {
    return {
        expired: value.expired,
        assets: from_candid_vec_n17(_uploadFile, _downloadFile, value.assets),
        timestamp: value.timestamp
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marketType: _MarketType;
    ticker: string;
    name: string;
}): {
    marketType: MarketType;
    ticker: string;
    name: string;
} {
    return {
        marketType: from_candid_MarketType_n20(_uploadFile, _downloadFile, value.marketType),
        ticker: value.ticker,
        name: value.name
    };
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _StocksVPS1ValidationResult]): [string, StocksVPS1ValidationResult] {
    return [
        value[0],
        from_candid_StocksVPS1ValidationResult_n10(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    valid: null;
} | {
    invalid: null;
}): Variant_valid_invalid {
    return "valid" in value ? Variant_valid_invalid.valid : "invalid" in value ? Variant_valid_invalid.invalid : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stocks: null;
} | {
    commodities: null;
} | {
    fiat: null;
} | {
    crypto: null;
}): MarketType {
    return "stocks" in value ? MarketType.stocks : "commodities" in value ? MarketType.commodities : "fiat" in value ? MarketType.fiat : "crypto" in value ? MarketType.crypto : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Asset>): Array<Asset> {
    return value.map((x)=>from_candid_Asset_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _StocksVPS1ValidationResult]>): Array<[string, StocksVPS1ValidationResult]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Asset_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Asset): _Asset {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_MarketType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketType): _MarketType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marketType: MarketType;
    ticker: string;
    name: string;
}): {
    marketType: _MarketType;
    ticker: string;
    name: string;
} {
    return {
        marketType: to_candid_MarketType_n6(_uploadFile, _downloadFile, value.marketType),
        ticker: value.ticker,
        name: value.name
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketType): {
    stocks: null;
} | {
    commodities: null;
} | {
    fiat: null;
} | {
    crypto: null;
} {
    return value == MarketType.stocks ? {
        stocks: null
    } : value == MarketType.commodities ? {
        commodities: null
    } : value == MarketType.fiat ? {
        fiat: null
    } : value == MarketType.crypto ? {
        crypto: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Asset>): Array<_Asset> {
    return value.map((x)=>to_candid_Asset_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
